### ISSUE TITLE
The run_FastQTL_threaded.py script produces different output files with the same input files for different chunks number

### ISSUE THREAD

**Issue by VekiJ** [broadinstitute/gtex-pipeline#25] opened 2019-04-18 15:45 UTC
I am trying to run the run_FastQTL_threaded.py script on the VCF and BED files which contain only chromosome 22 and I noticed that for the different number of chunks the output files are always different. Moreover, as I increase the number of chunks, the output file is smaller. I have checked all output log files and it seems that all the chunks are processed (I expected that some chunks were skipped because of the memory issue but it seems that this is not the case). I am sending you the command lines and the output file's sizes which are produced with these command lines. Please note that these are the command lines that I tried to run locally. But, I tried the same on the AWS m4.16 xlarge instance and the same problem exists there. Moreover, when I run this script on the VCF and BED files which contain all chromosomes, the output files are the same despite the different chunk size between tasks. Could you help me to understand why this is happening when I run the fastQTL tool on chromosome 22? 
I used BED file produced by the Geuvadis consortium and VCF file from the 1000 Genomes project. 

**Number of chunks 10:** 
**Command:**
/opt/fastqtl/python/run_FastQTL_threaded.py chr22.vcf.gz FastQTL.bed.gz chunks10 --window 1e6 --chunks 10 --threads 4
**Output file size:**
chunks10.allpairs.txt.gz - 317 MB

**Number of chunks 20:** 
**Command:**
/opt/fastqtl/python/run_FastQTL_threaded.py chr22.vcf.gz FastQTL.bed.gz chunks20 --window 1e6 --chunks 20 --threads 4
**Output file size:**
chunks20.allpairs.txt.gz - 312M 

**Number of chunks 30:** 
**Command:**
/opt/fastqtl/python/run_FastQTL_threaded.py chr22.vcf.gz FastQTL.bed.gz chunks30 --window 1e6 --chunks 30 --threads 4
**Output file size:**
chunks30.allpairs.txt.gz - 308 MB

**Number of chunks 100:** 
**Command:**
/opt/fastqtl/python/run_FastQTL_threaded.py chr22.vcf.gz FastQTL.bed.gz chunks100 --window 1e6 --chunks 100 --threads 4
**Output file size:**
chunks100.allpairs.txt.gz - 265 MB

**Comment by francois-a** [comment] 2019-08-16 22:24
Duplicate of https://github.com/francois-a/fastqtl/issues/8

**Closed by francois-a** 2019-08-16 22:24 UTC
